### ISSUE TITLE
Rebus.SimpleInjector 8.0.0 is locking the SimpleInjector container before registering components

### ISSUE THREAD

**Issue by renatogontijo** [rebus-org/Rebus.SimpleInjector#14]
I'm using the Rebus.SimpleInjector 7.0.0 with SimpleInjector container and Rebus is running without any problem. 
When I try to update to version 8.0.0, I have to use the new RegisterRebus function:

`Container container = (Container)containerRegistry.Container;

        container.RegisterRebus(
            configurer => configurer
                .Logging(l => l.Serilog())
                .Serialization(s => s.UseNewtonsoftJson(CreateNewtonsoftSettings(), Encoding.UTF8))
                .Options(o =>
                {
                    o.EnableSynchronousRequestReply();
                    o.SimpleRetryStrategy(rebusErrorQueue, maxDeliveryAttempts: 1);
                    o.SetNumberOfWorkers(2);
                    o.SetMaxParallelism(3);
                })
                .Transport(t => t.UseRabbitMq(rabbitMqConnectionString, rebusQueue)
                                 .Prefetch(2))
                .Routing(r =>
                {
                    r.TypeBased()
                        .MapAssemblyOf<IDomainNotification>(rebusQueue)
                        .MapAssemblyOf<DefaultReply>(rebusQueue)
                        .MapCommands(rebusQueue)
                        .MapEvents(rebusQueue);
                })
                .Sagas(sagas => sagas.StoreInMemory())
            );
`
But when I start the WebApi application with the version 8.0.0 the application throw the following error.

`[14:55:40 FTL] Host terminated unexpectedly
System.InvalidOperationException: The container can't be changed after the first call to GetInstance, GetAllInstances, Verify, and some calls of GetRegistration.`

Analysing Rebus.SimpleInjector 8.0.0 code in the [RegisterRebus method](https://github.com/rebus-org/Rebus.SimpleInjector/blob/master/Rebus.SimpleInjector/Config/SimpleInjectorConfigurationExtensions.cs), there is a call to container.GetInstance:

`var starter = container.GetInstance<IBusStarter>();`

The SimpleInjector container locks the container on first call on to some of the following methods: GetInstance, GetAllInstances, Verify. I guess this GetInstance is locking the container before the WebApi register all the objects on SimpleInjector

With the version 7.0.0 Rebus and SimpleInjector is running with no errors.

**Comment by mookid8000** [comment]
Could you post the entire stacktrace? It is not clear where the exception occurs.

**Comment by renatogontijo** [comment]
[09:48:31 FTL] Host terminated unexpectedly
System.InvalidOperationException: The container can't be changed after the first call to GetInstance, GetAllInstances, Verify, and some calls of GetRegistration. Please see https://simpleinjector.org/locked to understand why the container is locked. The following stack trace describes the location where the container was locked:

   at SimpleInjector.Container.GetInstance[TService]()
   at Rebus.Config.SimpleInjectorConfigurationExtensions.<>c__DisplayClass4_0.<RegisterRebus>b__5(Object _, ContainerLockingEventArgs _)
   at SimpleInjector.ContainerOptions.RaiseContainerLockingAndReset()
   at SimpleInjector.Container.NotifyAndLock()
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify(VerificationOption option)
   at SimpleInjector.Container.Verify()
   at AgroHUB.Sume.Infra.ServiceContainer.SimpleInjector.ContainerRegistry.SimpleInjectorContainerRegistry.ConfigureServiceContainer(IApplicationBuilder app, IWebHostEnvironment env)
   at AgroHUB.IndividualControl.Application.Api.Configurations.BusConfiguration.UseRebus(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\Usuário\OneDrive\Documentos\Projects\AgroHUB.IndividualControl\src\AgroHUB.IndividualControl.Application.Api\Configurations\BusConfiguration.cs:line 39
   at AgroHUB.IndividualControl.Services.Api.Startup.Configure(WebApplication app, IWebHostEnvironment env) in C:\Users\Usuário\OneDrive\Documentos\Projects\AgroHUB.IndividualControl\src\AgroHUB.IndividualControl.Services.Api\Startup.cs:line 53
   at AgroHUB.Sume.Endpoint.Abstractions.Extensions.StartupExtension.UseStartup[TWebStartup](WebApplicationBuilder webAppBuilder, String url)
   at Program.<Main>$(String[] args) in C:\Users\Usuário\OneDrive\Documentos\Projects\AgroHUB.IndividualControl\src\AgroHUB.IndividualControl.Services.Api\Program.cs:line 15

   at SimpleInjector.Container.ThrowWhenContainerIsLockedOrDisposed()
   at SimpleInjector.Container.add_ResolveUnregisteredType(EventHandler`1 value)
   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.<>c__DisplayClass14_0.<AddAutoCrossWiring>b__0(Object _, ContainerLockingEventArgs __)
   at SimpleInjector.ContainerOptions.RaiseContainerLockingAndReset()
   at SimpleInjector.Container.NotifyAndLock()
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify(VerificationOption option)
   at SimpleInjector.Container.Verify()
   at AgroHUB.Sume.Infra.ServiceContainer.SimpleInjector.ContainerRegistry.SimpleInjectorContainerRegistry.ConfigureServiceContainer(IApplicationBuilder app, IWebHostEnvironment env)
   at AgroHUB.IndividualControl.Application.Api.Configurations.BusConfiguration.UseRebus(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\Usuário\OneDrive\Documentos\Projects\AgroHUB.IndividualControl\src\AgroHUB.IndividualControl.Application.Api\Configurations\BusConfiguration.cs:line 39
   at AgroHUB.IndividualControl.Services.Api.Startup.Configure(WebApplication app, IWebHostEnvironment env) in C:\Users\Usuário\OneDrive\Documentos\Projects\AgroHUB.IndividualControl\src\AgroHUB.IndividualControl.Services.Api\Startup.cs:line 53
   at AgroHUB.Sume.Endpoint.Abstractions.Extensions.StartupExtension.UseStartup[TWebStartup](WebApplicationBuilder webAppBuilder, String url)
   at Program.<Main>$(String[] args) in C:\Users\Usuário\OneDrive\Documentos\Projects\AgroHUB.IndividualControl\src\AgroHUB.IndividualControl.Services.Api\Program.cs:line 15

**Comment by mookid8000** [comment]
ah ok so the locking seems to be caused by [this line](https://github.com/rebus-org/Rebus.SimpleInjector/blob/master/Rebus.SimpleInjector/Config/SimpleInjectorConfigurationExtensions.cs#L102), which is a function subscribed to the container's `ContainerLocking` event.

As stated in [the docs for ContainerLocking](https://simpleinjector.org/ReferenceLibrary/html/E_SimpleInjector_ContainerOptions_ContainerLocking.htm), it's OK-but-not-advised to e.g. call `GetInstance` from the callback, because it prevents subsequent callbacks' ability to make further registrations.

I'm guessing in your case that you are in fact making additional container registrations in the `ContainerLocking` callback? In any case, I've made a change that I think will solve your problem.

In Rebus.SimpleInjector 8.0.1 (which is on NuGet.org now 🙂 ) I've changed the order of the actions performed in the callback, which should make it possible for you to go

```csharp
container.RegisterRebus(
    (...),
    startAutomatically: false
);
```

followed by

```csharp
container.StartBus();
```

later, when you are ready.

I hope it works out for you 🙂

**Comment by renatogontijo** [comment]
Now worked for me, but only with the following steps.

I registered the Rebus with

`container.RegisterRebus(
    (...),
    startAutomatically: false
);`

But if I call StartRebus() method, program throw the folowing exception:

`
[13:16:53 FTL] Host terminated unexpectedly
System.InvalidOperationException: No service for type 'Rebus.ServiceProvider.Internals.RebusDisposalHelper' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Rebus.Config.ServiceProviderExtensions.<>c__DisplayClass0_0.<<StartRebus>g__StartHostedServices|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Rebus.ServiceProvider.Internals.AsyncHelpers.CustomSynchronizationContext.<Run>b__7_0(Object _)
   at Rebus.ServiceProvider.Internals.AsyncHelpers.CustomSynchronizationContext.Run()
   at Rebus.ServiceProvider.Internals.AsyncHelpers.RunSync(Func``1 task)
   at Rebus.Config.ServiceProviderExtensions.StartRebus(IServiceProvider serviceProvider)
   at AgroHUB.Sume.Infra.Bus.Rebus.Configurer.SimpleInjectorContainerConfigurer.RegisterInRabbitMQ(IContainerRegistry containerRegistry)
   at AgroHUB.Sume.Infra.Bus.Rebus.Extensions.RebusExtension.RegisterRebusRabbitMQ(IContainerRegistry containerRegistry, String queueName, String rabbitMqHost, Int32 rabbitMqAmqpPort, String rabbitMqUsername, String rabbitMqPassword)
   at AgroHUB.Sume.Endpoint.Abstractions.Configurations.BusConfiguration.ConfigureRebus(IContainerRegistry containerRegistry, IConfiguration configuration, Assembly assembly)
   at AgroHUB.IndividualControl.Services.Api.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Usuário\OneDrive\Documentos\Projects\AgroHUB.IndividualControl\src\AgroHUB.IndividualControl.Services.Api\Startup.cs:line 44
   at AgroHUB.Sume.Endpoint.Abstractions.Extensions.StartupExtension.UseStartup[TWebStartup](WebApplicationBuilder webAppBuilder, String url)
   at Program.<Main>$(String[] args) in C:\Users\Usuário\OneDrive\Documentos\Projects\AgroHUB.IndividualControl\src\AgroHUB.IndividualControl.Services.Api\Program.cs:line 15
`

But if I use the StartBus() method of SimpleInjector before subscribe events the program runs with no errors.

Thanks!

**Comment by mookid8000** [comment]
> But if I use the StartBus() method of SimpleInjector before subscribe events the program runs with no errors.

Oh yeah sorry, I accidentally typed `StartRebus()`, but you're correct – the extension to call when using SimpleInjector is called `StartBus()`.

It looks like you're referencing the Rebus.ServiceProvider NuGet package – you should probably remove that dependency, as you have no need for it.
