### ISSUE TITLE
[InvalidOperationException: The container can't be changed

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus.SimpleInjector#4]
After upgrading from 2.0 I'm getting this error from SimpleInjector.  I looked at the code for the `SimpleInjectorContainerAdapter` and it looks like the container isn't being called to register like it used to in previous versions.  Should I be calling rebus differently now somehow?

Here's my registration
            var adapter = new SimpleInjectorContainerAdapter(container);

            Configure
                .With(adapter)
                .Options(o =>
                {
                    o.SimpleRetryStrategy("goPMO.Impel.Messages.Errors");
                    o.Decorate<IPipeline>(c =>
                    {
                        var pipeline = c.Get<IPipeline>();
                        return
                            new PipelineStepInjector(pipeline).OnSend(
                                new TenantIdOutgoingMutator(container.GetInstance<IGetUserSettings>),
                                PipelineRelativePosition.Before, typeof(SerializeOutgoingMessageStep));
                    });
                    o.LogPipeline();
                })
                .Serialization(s =>
                {
                    var reSettings = new JsonSerializerSettings
                    {
                        TypeNameHandling = TypeNameHandling.All,
                        NullValueHandling = NullValueHandling.Include,
                    };
                    reSettings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
                    reSettings.Converters.Add(new StringEnumConverter());
                    s.UseNewtonsoftJson(reSettings);
                })
                .Logging(l => l.Serilog(Log.Logger))
                .Transport(s => s.UseSqlServerAsOneWayClient("SQLMessageQueue", "RebusImpelMessages"))
                .Subscriptions(s => s.StoreInSqlServer("SQLMessageQueue", "RebusImpelSubscriptions", true))
                .Routing(r => r.TypeBased().MapAssemblyOf<CreateProject>("goPMO.Impel.Service"))
                .Start();

And Here is the call stack
	`[InvalidOperationException: The container can't be changed after the first call to GetInstance, GetAllInstances, Verify, and some calls of GetRegistration. Please see https://simpleinjector.org/locked to understand why the container is locked. The following stack trace describes the location where the container was locked:`
	   at System.Lazy`1.CreateValue()
	   at System.Lazy`1.LazyInitValue()
	   at System.Lazy`1.get_Value()
	   at SimpleInjector.InstanceProducer.BuildInstanceCreator()
	   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
	   at SimpleInjector.InstanceProducer.GetInstance()
	   at Rebus.SimpleInjector.SimpleInjectorContainerAdapter.SetBus(IBus bus)
	   at Rebus.Config.RebusConfigurer.Start()
	   at goPMO.Impel.Api.CompositionRoot.SimpleInjectorExtensions.RegisterRebus(Container container) in C:\Projects\goPMO\Impel-Api-2.0\source\WebApi\CompositionRoot\SimpleInjectorExtensions.cs:line 423
	   at goPMO.Impel.Api.CompositionRoot.Bootstrapper.Bootstrap(IAppBuilder app, HttpConfiguration config) in C:\Projects\goPMO\Impel-Api-2.0\source\WebApi\CompositionRoot\Bootstrapper.cs:line 72
	   at goPMO.Impel.Api.CompositionRoot.DebugStartup.Configuration(IAppBuilder app) in C:\Projects\goPMO\Impel-Api-2.0\source\WebApi\CompositionRoot\DebugStartup.cs:line 24
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
	   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
	   at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
	   at Microsoft.Owin.Host.SystemWeb.OwinHttpModule.<>c__DisplayClass2.<InitializeBlueprint>b__0(IAppBuilder builder)
	   at Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup)
	   at Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup)
	   at Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint()
	   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
	   at Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context)
	   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
	   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
	   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
	   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)

**Comment by stevengopmo** [comment]
moving the rebus configuration to the very last thing I do before calling `container.Verify` seems to work but why?  It didn't seem to matter before.

**Comment by mookid8000** [comment]
Yes, the way Rebus is configured with SimpleInjector has been changed to properly fit into the [RRR](http://blog.ploeh.dk/2010/09/29/TheRegisterResolveReleasepattern/) pattern encouraged by the container.

You can see an example on how to go about configuring it [here](https://github.com/rebus-org/Rebus.SimpleInjector/blob/master/Rebus.SimpleInjector.Tests/TestRealisticConfigurationScenario.cs#L33-L46)

and because I have nothing better to do right now, I have copied the code sample to here – it looks like this:
```csharp
container.ConfigureRebus(
    configurer => configurer
        .Transport(t => t.UseInMemoryTransport(new InMemNetwork(), "test"))
        .Start()
);
```

**Comment by stevengopmo** [comment]
awesome! thank you very much

**Comment by stevengopmo** [comment]
and I do apologize, I see it's even documented as such.  Sorry about that I will be more diligent in the future.

**Comment by stevengopmo** [comment]
OK, this is really strange, the extension method does not show up for me.  I'm using .NET 4.7.1 does that make a difference?  I know it's probably something stupid on my side but any ideas?

**Comment by stevengopmo** [comment]
![image](https://user-images.githubusercontent.com/14218631/38421951-f6ca991a-3976-11e8-89df-89813cb5068a.png)

hmmmm.  I open the .dll in dotPeek and no extensions.  Am I missing an extra package or something?

**Comment by mookid8000** [comment]
oh sorry, I think you need to

    Update-Package Rebus.SimpleInjector -Pre

so you get the betaversion
